name: Linting and Test

on: pull_request

jobs:
  set-up:
    name: ğŸ“‹ Pull Request Checklist
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Node Set up âš™ï¸
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Packages
        run: npm install

      - name: Run ESLint âœ…
        run: npx eslint .

      - name: Run Test ğŸš¨
        run: npm test
